[project]
name = "neuralib-atlas"
version = "0.7.0"
requires-python = ">=3.11,<3.13"
description = "Tools for hierarchical representations of the mouse brain anatomy"
authors = [
    { name = "Yu-Ting Wei", email = "ytsimon2004@gmail.com" },
]
license = { text = "BSD-3-Clause" }
readme = "README.md"
keywords = ["Parser", "Segmentation", "Morphology"]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    'Intended Audience :: Science/Research',
    "Typing :: Typed",
]

dependencies = [
    "neuralib-utils[all]>=0.7.0",
    "pynrrd",
    "openpyxl",
    "anytree",
    "plotly",
    "fastexcel",
]

[project.optional-dependencies]

brainrender = [
    "brainrender",
    "numba>=0.63", # Override old numba from brainrender for Python 3.11+ support
    "argclz"
]

all = ["neuralib-atlas[brainrender]"]

[project.urls]
Homepage = "https://github.com/ytsimon2004/neuralib2"
Documentation = "https://neuralib2.readthedocs.io/en/latest/index.html"
Repository = "https://github.com/ytsimon2004/neuralib2"
Issues = "https://github.com/ytsimon2004/neuralib2/issues"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[tool.setuptools.packages.find]
where = ["src"]


[project.scripts]
nl_brainrender = "neuralib.atlas.brainrender.main_app:main"