[project]
name = "neuralib-imaging"
version = "0.7.0"
requires-python = ">=3.11,<3.13"
description = "Tools for cellular imaging and widefield imaging"
authors = [
    { name = "Yu-Ting Wei", email = "ytsimon2004@gmail.com" },
]
license = { text = "BSD-3-Clause" }
readme = "README.md"
keywords = ["Parser", "Segmentation", "Morphology"]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    'Intended Audience :: Science/Research',
    "Typing :: Typed",
]

dependencies = [
    "neuralib-utils[all]>=0.7.0",
    "numpy",
    "numba",
    "matplotlib",
]

[project.optional-dependencies]

cascade = ["ruamel.yaml", "tensorflow"]
widefield = ["napari", "bokeh", "scikit-learn"]

all = ["neuralib-imaging[cascade]", "neuralib-imaging[widefield]"]

[project.urls]
Homepage = "https://github.com/ytsimon2004/neuralib2"
Documentation = "https://neuralib2.readthedocs.io/en/latest/index.html"
Repository = "https://github.com/ytsimon2004/neuralib2"
Issues = "https://github.com/ytsimon2004/neuralib2/issues"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[tool.setuptools.packages.find]
where = ["src"]