[project]
name = "neuralib-parser"
version = "0.7.0"
requires-python = ">=3.11,<3.13"
description = "Parsers for output from open-source packages or specific devices"
authors = [
    { name = "Yu-Ting Wei", email = "ytsimon2004@gmail.com" },
    { name = "Ta-Shun Su", email = "antoniost29@gmail.com" }
]
license = { text = "BSD-3-Clause" }
readme = "README.md"
keywords = ["Parser", "Segmentation", "Morphology"]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    'Intended Audience :: Science/Research',
    "Typing :: Typed",
]

dependencies = [
    "neuralib-utils[all]>=0.7.0",
    "numpy",
]

[project.optional-dependencies]

stardist = ["stardist", "roifile", "tensorflow", "numpy<2.0; extra == 'stardist'", "napari"]
suite2p = ["neuralib-imaging>=0.7.0"]
czi = ["aicspylibczi", "xmltodict"]
sbx = ["sbxreader"]

all = [
    "neuralib-parser[suite2p]",
    "neuralib-parser[sbx]",
    "tifffile"
]

[project.urls]
Homepage = "https://github.com/ytsimon2004/neuralib2"
Documentation = "https://neuralib2.readthedocs.io/en/latest/index.html"
Repository = "https://github.com/ytsimon2004/neuralib2"
Issues = "https://github.com/ytsimon2004/neuralib2/issues"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[tool.setuptools.packages.find]
where = ["src"]